# Generated by Django 5.1.3 on 2024-11-14 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.IntegerField(verbose_name='Price')),
                ('short_description', models.CharField(db_index=True, max_length=360, null=True, verbose_name='Short Description')),
                ('description', models.TextField(db_index=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active / inactive')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True)),
                ('is_deleted', models.BooleanField(verbose_name='Deleted / NoDeleted')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': "Product's",
            },
        ),
        migrations.CreateModel(
            name='productCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(verbose_name='Active / Inactive')),
                ('is_deleted', models.BooleanField(verbose_name='Deleted / NoDeleted')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': "Category's",
            },
        ),
        migrations.CreateModel(
            name='Product_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(db_index=True, max_length=50, verbose_name='Tag')),
                ('product_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productTags', to='product_module.product')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_Category', to='product_module.productcategory', verbose_name="Category's"),
        ),
    ]
