# Generated by Django 5.1.3 on 2024-12-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0004_productcategory_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_brands",
            name="url_title",
            field=models.CharField(
                db_index=True,
                default="url_title",
                max_length=300,
                verbose_name="عنوان در دامنه",
            ),
            preserve_default=False,
        ),
    ]
