# Generated by Django 5.1.3 on 2025-01-12 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_module", "0005_product_brands_url_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="خرید نهایی شده؟"),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ برداخت"
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="صاحب سبد خرید",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="Order_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="قیمت نهایی  تکی محثول"
                    ),
                ),
                ("count", models.IntegerField(verbose_name="تعداد")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_module.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_module.order_model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Detail",
                "verbose_name_plural": "Order Details",
            },
        ),
    ]
