# Generated by Django 5.1.3 on 2024-11-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_module", "0004_slider"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active / Inactive"),
        ),
    ]
