# Generated by Django 5.1.3 on 2024-11-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_module", "0002_createprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createprofile",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
    ]
