# Generated by Django 5.1.3 on 2024-11-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecategory",
            name="url_title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="عنوان لینک"
            ),
        ),
    ]
