# Generated by Django 5.1.3 on 2024-12-02 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_alter_article_comments_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article_comments',
            new_name='ArticleComments',
        ),
    ]
