# Generated by Django 5.1.3 on 2024-12-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_module", "0006_user_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
    ]
